language: javascript
before_install:
 - chmod +x build.sh
 - chmod +x deploy.sh
install:
  - npm install
script: ./build.sh
# safelist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
env:
  global:
    - GITHUB_REPO: "rhogeranacleto/rhogeranacleto.guthub.io"